### ISSUE TITLE
Auto DB dump and import to local

### ISSUE THREAD

**Issue by janithcooray** [janithcooray/sync-stat#15]
Adding an option to download a DB copy directly from the DB server or import from a SQL dump

```yaml
database:
  driver: mysql
  profile: staging
  method: [ export | dump ]
  file: [ ./relative | /absolute ]/path/to/dump.sql
  server:
    database_user: 
    database_name:
    database_pass:
    host:
    port: 
  local:
    database_user: 
    database_name:
    database_pass:
    root_password:
    host:
    port: 
```

**Comment by janithcooray** [comment]
@BlazeIsClone what do you think?

**Comment by BlazeIsClone** [comment]
Dev XP +💯

**Comment by vimarshacooray** [comment]
Update to usage

```yml
database:
  driver: mysql
  method: dump 
  server: 
    database_user: name
    database_name: name
    database_pass: name
    host: 0.0.0.0
    port: 3306
  local: 
    provision: true # will remove tables if they exist
    method: [CLIENT,DOCKER,CLI,SSH]
    container_name: #for Docker method
    ssh_key: /path/to/ssh/file
    database_user: wordpress
    database_name: wordpress
    database_pass: wordpress
    root_password: somewordpress # Required for provision
    host: localhost
    port: 3306
  ```

Status Dumps fully work.
Imports are still janky. only `CLIENT` method works but too slow
